profile = { default = { libs = ["node_modules", "lib"] } }
[default]
src = 'src'
out = 'out'
libs = ['node_modules']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config